/**
 * The classes, interfaces and enums in this package are generated automatically and therefore not properly documented.
 *
 * @author automatically generated by Apache Thrift (based on a specification by strut1, touwm1 &amp; weidj1)
 */
package ch.bfh.progressor.executor.thrift;
