/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ch.bfh.progressor.executor;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-12-02")
public class TestCase implements org.apache.thrift.TBase<TestCase, TestCase._Fields>, java.io.Serializable, Cloneable, Comparable<TestCase> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TestCase");

  private static final org.apache.thrift.protocol.TField FUNCTION_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("functionName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INPUT_TYPES_FIELD_DESC = new org.apache.thrift.protocol.TField("inputTypes", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField INPUT_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("inputValues", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField OUTPUT_TYPES_FIELD_DESC = new org.apache.thrift.protocol.TField("outputTypes", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField EXPECTED_OUTPUT_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("expectedOutputValues", org.apache.thrift.protocol.TType.LIST, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TestCaseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TestCaseTupleSchemeFactory());
  }

  public String functionName; // required
  public List<String> inputTypes; // required
  public List<String> inputValues; // required
  public List<String> outputTypes; // required
  public List<String> expectedOutputValues; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FUNCTION_NAME((short)1, "functionName"),
    INPUT_TYPES((short)2, "inputTypes"),
    INPUT_VALUES((short)3, "inputValues"),
    OUTPUT_TYPES((short)4, "outputTypes"),
    EXPECTED_OUTPUT_VALUES((short)5, "expectedOutputValues");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FUNCTION_NAME
          return FUNCTION_NAME;
        case 2: // INPUT_TYPES
          return INPUT_TYPES;
        case 3: // INPUT_VALUES
          return INPUT_VALUES;
        case 4: // OUTPUT_TYPES
          return OUTPUT_TYPES;
        case 5: // EXPECTED_OUTPUT_VALUES
          return EXPECTED_OUTPUT_VALUES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FUNCTION_NAME, new org.apache.thrift.meta_data.FieldMetaData("functionName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INPUT_TYPES, new org.apache.thrift.meta_data.FieldMetaData("inputTypes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.INPUT_VALUES, new org.apache.thrift.meta_data.FieldMetaData("inputValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.OUTPUT_TYPES, new org.apache.thrift.meta_data.FieldMetaData("outputTypes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.EXPECTED_OUTPUT_VALUES, new org.apache.thrift.meta_data.FieldMetaData("expectedOutputValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TestCase.class, metaDataMap);
  }

  public TestCase() {
  }

  public TestCase(
    String functionName,
    List<String> inputTypes,
    List<String> inputValues,
    List<String> outputTypes,
    List<String> expectedOutputValues)
  {
    this();
    this.functionName = functionName;
    this.inputTypes = inputTypes;
    this.inputValues = inputValues;
    this.outputTypes = outputTypes;
    this.expectedOutputValues = expectedOutputValues;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TestCase(TestCase other) {
    if (other.isSetFunctionName()) {
      this.functionName = other.functionName;
    }
    if (other.isSetInputTypes()) {
      List<String> __this__inputTypes = new ArrayList<String>(other.inputTypes);
      this.inputTypes = __this__inputTypes;
    }
    if (other.isSetInputValues()) {
      List<String> __this__inputValues = new ArrayList<String>(other.inputValues);
      this.inputValues = __this__inputValues;
    }
    if (other.isSetOutputTypes()) {
      List<String> __this__outputTypes = new ArrayList<String>(other.outputTypes);
      this.outputTypes = __this__outputTypes;
    }
    if (other.isSetExpectedOutputValues()) {
      List<String> __this__expectedOutputValues = new ArrayList<String>(other.expectedOutputValues);
      this.expectedOutputValues = __this__expectedOutputValues;
    }
  }

  public TestCase deepCopy() {
    return new TestCase(this);
  }

  @Override
  public void clear() {
    this.functionName = null;
    this.inputTypes = null;
    this.inputValues = null;
    this.outputTypes = null;
    this.expectedOutputValues = null;
  }

  public String getFunctionName() {
    return this.functionName;
  }

  public TestCase setFunctionName(String functionName) {
    this.functionName = functionName;
    return this;
  }

  public void unsetFunctionName() {
    this.functionName = null;
  }

  /** Returns true if field functionName is set (has been assigned a value) and false otherwise */
  public boolean isSetFunctionName() {
    return this.functionName != null;
  }

  public void setFunctionNameIsSet(boolean value) {
    if (!value) {
      this.functionName = null;
    }
  }

  public int getInputTypesSize() {
    return (this.inputTypes == null) ? 0 : this.inputTypes.size();
  }

  public java.util.Iterator<String> getInputTypesIterator() {
    return (this.inputTypes == null) ? null : this.inputTypes.iterator();
  }

  public void addToInputTypes(String elem) {
    if (this.inputTypes == null) {
      this.inputTypes = new ArrayList<String>();
    }
    this.inputTypes.add(elem);
  }

  public List<String> getInputTypes() {
    return this.inputTypes;
  }

  public TestCase setInputTypes(List<String> inputTypes) {
    this.inputTypes = inputTypes;
    return this;
  }

  public void unsetInputTypes() {
    this.inputTypes = null;
  }

  /** Returns true if field inputTypes is set (has been assigned a value) and false otherwise */
  public boolean isSetInputTypes() {
    return this.inputTypes != null;
  }

  public void setInputTypesIsSet(boolean value) {
    if (!value) {
      this.inputTypes = null;
    }
  }

  public int getInputValuesSize() {
    return (this.inputValues == null) ? 0 : this.inputValues.size();
  }

  public java.util.Iterator<String> getInputValuesIterator() {
    return (this.inputValues == null) ? null : this.inputValues.iterator();
  }

  public void addToInputValues(String elem) {
    if (this.inputValues == null) {
      this.inputValues = new ArrayList<String>();
    }
    this.inputValues.add(elem);
  }

  public List<String> getInputValues() {
    return this.inputValues;
  }

  public TestCase setInputValues(List<String> inputValues) {
    this.inputValues = inputValues;
    return this;
  }

  public void unsetInputValues() {
    this.inputValues = null;
  }

  /** Returns true if field inputValues is set (has been assigned a value) and false otherwise */
  public boolean isSetInputValues() {
    return this.inputValues != null;
  }

  public void setInputValuesIsSet(boolean value) {
    if (!value) {
      this.inputValues = null;
    }
  }

  public int getOutputTypesSize() {
    return (this.outputTypes == null) ? 0 : this.outputTypes.size();
  }

  public java.util.Iterator<String> getOutputTypesIterator() {
    return (this.outputTypes == null) ? null : this.outputTypes.iterator();
  }

  public void addToOutputTypes(String elem) {
    if (this.outputTypes == null) {
      this.outputTypes = new ArrayList<String>();
    }
    this.outputTypes.add(elem);
  }

  public List<String> getOutputTypes() {
    return this.outputTypes;
  }

  public TestCase setOutputTypes(List<String> outputTypes) {
    this.outputTypes = outputTypes;
    return this;
  }

  public void unsetOutputTypes() {
    this.outputTypes = null;
  }

  /** Returns true if field outputTypes is set (has been assigned a value) and false otherwise */
  public boolean isSetOutputTypes() {
    return this.outputTypes != null;
  }

  public void setOutputTypesIsSet(boolean value) {
    if (!value) {
      this.outputTypes = null;
    }
  }

  public int getExpectedOutputValuesSize() {
    return (this.expectedOutputValues == null) ? 0 : this.expectedOutputValues.size();
  }

  public java.util.Iterator<String> getExpectedOutputValuesIterator() {
    return (this.expectedOutputValues == null) ? null : this.expectedOutputValues.iterator();
  }

  public void addToExpectedOutputValues(String elem) {
    if (this.expectedOutputValues == null) {
      this.expectedOutputValues = new ArrayList<String>();
    }
    this.expectedOutputValues.add(elem);
  }

  public List<String> getExpectedOutputValues() {
    return this.expectedOutputValues;
  }

  public TestCase setExpectedOutputValues(List<String> expectedOutputValues) {
    this.expectedOutputValues = expectedOutputValues;
    return this;
  }

  public void unsetExpectedOutputValues() {
    this.expectedOutputValues = null;
  }

  /** Returns true if field expectedOutputValues is set (has been assigned a value) and false otherwise */
  public boolean isSetExpectedOutputValues() {
    return this.expectedOutputValues != null;
  }

  public void setExpectedOutputValuesIsSet(boolean value) {
    if (!value) {
      this.expectedOutputValues = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FUNCTION_NAME:
      if (value == null) {
        unsetFunctionName();
      } else {
        setFunctionName((String)value);
      }
      break;

    case INPUT_TYPES:
      if (value == null) {
        unsetInputTypes();
      } else {
        setInputTypes((List<String>)value);
      }
      break;

    case INPUT_VALUES:
      if (value == null) {
        unsetInputValues();
      } else {
        setInputValues((List<String>)value);
      }
      break;

    case OUTPUT_TYPES:
      if (value == null) {
        unsetOutputTypes();
      } else {
        setOutputTypes((List<String>)value);
      }
      break;

    case EXPECTED_OUTPUT_VALUES:
      if (value == null) {
        unsetExpectedOutputValues();
      } else {
        setExpectedOutputValues((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FUNCTION_NAME:
      return getFunctionName();

    case INPUT_TYPES:
      return getInputTypes();

    case INPUT_VALUES:
      return getInputValues();

    case OUTPUT_TYPES:
      return getOutputTypes();

    case EXPECTED_OUTPUT_VALUES:
      return getExpectedOutputValues();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FUNCTION_NAME:
      return isSetFunctionName();
    case INPUT_TYPES:
      return isSetInputTypes();
    case INPUT_VALUES:
      return isSetInputValues();
    case OUTPUT_TYPES:
      return isSetOutputTypes();
    case EXPECTED_OUTPUT_VALUES:
      return isSetExpectedOutputValues();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TestCase)
      return this.equals((TestCase)that);
    return false;
  }

  public boolean equals(TestCase that) {
    if (that == null)
      return false;

    boolean this_present_functionName = true && this.isSetFunctionName();
    boolean that_present_functionName = true && that.isSetFunctionName();
    if (this_present_functionName || that_present_functionName) {
      if (!(this_present_functionName && that_present_functionName))
        return false;
      if (!this.functionName.equals(that.functionName))
        return false;
    }

    boolean this_present_inputTypes = true && this.isSetInputTypes();
    boolean that_present_inputTypes = true && that.isSetInputTypes();
    if (this_present_inputTypes || that_present_inputTypes) {
      if (!(this_present_inputTypes && that_present_inputTypes))
        return false;
      if (!this.inputTypes.equals(that.inputTypes))
        return false;
    }

    boolean this_present_inputValues = true && this.isSetInputValues();
    boolean that_present_inputValues = true && that.isSetInputValues();
    if (this_present_inputValues || that_present_inputValues) {
      if (!(this_present_inputValues && that_present_inputValues))
        return false;
      if (!this.inputValues.equals(that.inputValues))
        return false;
    }

    boolean this_present_outputTypes = true && this.isSetOutputTypes();
    boolean that_present_outputTypes = true && that.isSetOutputTypes();
    if (this_present_outputTypes || that_present_outputTypes) {
      if (!(this_present_outputTypes && that_present_outputTypes))
        return false;
      if (!this.outputTypes.equals(that.outputTypes))
        return false;
    }

    boolean this_present_expectedOutputValues = true && this.isSetExpectedOutputValues();
    boolean that_present_expectedOutputValues = true && that.isSetExpectedOutputValues();
    if (this_present_expectedOutputValues || that_present_expectedOutputValues) {
      if (!(this_present_expectedOutputValues && that_present_expectedOutputValues))
        return false;
      if (!this.expectedOutputValues.equals(that.expectedOutputValues))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_functionName = true && (isSetFunctionName());
    list.add(present_functionName);
    if (present_functionName)
      list.add(functionName);

    boolean present_inputTypes = true && (isSetInputTypes());
    list.add(present_inputTypes);
    if (present_inputTypes)
      list.add(inputTypes);

    boolean present_inputValues = true && (isSetInputValues());
    list.add(present_inputValues);
    if (present_inputValues)
      list.add(inputValues);

    boolean present_outputTypes = true && (isSetOutputTypes());
    list.add(present_outputTypes);
    if (present_outputTypes)
      list.add(outputTypes);

    boolean present_expectedOutputValues = true && (isSetExpectedOutputValues());
    list.add(present_expectedOutputValues);
    if (present_expectedOutputValues)
      list.add(expectedOutputValues);

    return list.hashCode();
  }

  @Override
  public int compareTo(TestCase other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFunctionName()).compareTo(other.isSetFunctionName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFunctionName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.functionName, other.functionName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInputTypes()).compareTo(other.isSetInputTypes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInputTypes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inputTypes, other.inputTypes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInputValues()).compareTo(other.isSetInputValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInputValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inputValues, other.inputValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOutputTypes()).compareTo(other.isSetOutputTypes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutputTypes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outputTypes, other.outputTypes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExpectedOutputValues()).compareTo(other.isSetExpectedOutputValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpectedOutputValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expectedOutputValues, other.expectedOutputValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TestCase(");
    boolean first = true;

    sb.append("functionName:");
    if (this.functionName == null) {
      sb.append("null");
    } else {
      sb.append(this.functionName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("inputTypes:");
    if (this.inputTypes == null) {
      sb.append("null");
    } else {
      sb.append(this.inputTypes);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("inputValues:");
    if (this.inputValues == null) {
      sb.append("null");
    } else {
      sb.append(this.inputValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("outputTypes:");
    if (this.outputTypes == null) {
      sb.append("null");
    } else {
      sb.append(this.outputTypes);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("expectedOutputValues:");
    if (this.expectedOutputValues == null) {
      sb.append("null");
    } else {
      sb.append(this.expectedOutputValues);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TestCaseStandardSchemeFactory implements SchemeFactory {
    public TestCaseStandardScheme getScheme() {
      return new TestCaseStandardScheme();
    }
  }

  private static class TestCaseStandardScheme extends StandardScheme<TestCase> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TestCase struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FUNCTION_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.functionName = iprot.readString();
              struct.setFunctionNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INPUT_TYPES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.inputTypes = new ArrayList<String>(_list0.size);
                String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.inputTypes.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setInputTypesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // INPUT_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                struct.inputValues = new ArrayList<String>(_list3.size);
                String _elem4;
                for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                {
                  _elem4 = iprot.readString();
                  struct.inputValues.add(_elem4);
                }
                iprot.readListEnd();
              }
              struct.setInputValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OUTPUT_TYPES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list6 = iprot.readListBegin();
                struct.outputTypes = new ArrayList<String>(_list6.size);
                String _elem7;
                for (int _i8 = 0; _i8 < _list6.size; ++_i8)
                {
                  _elem7 = iprot.readString();
                  struct.outputTypes.add(_elem7);
                }
                iprot.readListEnd();
              }
              struct.setOutputTypesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // EXPECTED_OUTPUT_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list9 = iprot.readListBegin();
                struct.expectedOutputValues = new ArrayList<String>(_list9.size);
                String _elem10;
                for (int _i11 = 0; _i11 < _list9.size; ++_i11)
                {
                  _elem10 = iprot.readString();
                  struct.expectedOutputValues.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setExpectedOutputValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TestCase struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.functionName != null) {
        oprot.writeFieldBegin(FUNCTION_NAME_FIELD_DESC);
        oprot.writeString(struct.functionName);
        oprot.writeFieldEnd();
      }
      if (struct.inputTypes != null) {
        oprot.writeFieldBegin(INPUT_TYPES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.inputTypes.size()));
          for (String _iter12 : struct.inputTypes)
          {
            oprot.writeString(_iter12);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.inputValues != null) {
        oprot.writeFieldBegin(INPUT_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.inputValues.size()));
          for (String _iter13 : struct.inputValues)
          {
            oprot.writeString(_iter13);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.outputTypes != null) {
        oprot.writeFieldBegin(OUTPUT_TYPES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.outputTypes.size()));
          for (String _iter14 : struct.outputTypes)
          {
            oprot.writeString(_iter14);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.expectedOutputValues != null) {
        oprot.writeFieldBegin(EXPECTED_OUTPUT_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.expectedOutputValues.size()));
          for (String _iter15 : struct.expectedOutputValues)
          {
            oprot.writeString(_iter15);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TestCaseTupleSchemeFactory implements SchemeFactory {
    public TestCaseTupleScheme getScheme() {
      return new TestCaseTupleScheme();
    }
  }

  private static class TestCaseTupleScheme extends TupleScheme<TestCase> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TestCase struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFunctionName()) {
        optionals.set(0);
      }
      if (struct.isSetInputTypes()) {
        optionals.set(1);
      }
      if (struct.isSetInputValues()) {
        optionals.set(2);
      }
      if (struct.isSetOutputTypes()) {
        optionals.set(3);
      }
      if (struct.isSetExpectedOutputValues()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetFunctionName()) {
        oprot.writeString(struct.functionName);
      }
      if (struct.isSetInputTypes()) {
        {
          oprot.writeI32(struct.inputTypes.size());
          for (String _iter16 : struct.inputTypes)
          {
            oprot.writeString(_iter16);
          }
        }
      }
      if (struct.isSetInputValues()) {
        {
          oprot.writeI32(struct.inputValues.size());
          for (String _iter17 : struct.inputValues)
          {
            oprot.writeString(_iter17);
          }
        }
      }
      if (struct.isSetOutputTypes()) {
        {
          oprot.writeI32(struct.outputTypes.size());
          for (String _iter18 : struct.outputTypes)
          {
            oprot.writeString(_iter18);
          }
        }
      }
      if (struct.isSetExpectedOutputValues()) {
        {
          oprot.writeI32(struct.expectedOutputValues.size());
          for (String _iter19 : struct.expectedOutputValues)
          {
            oprot.writeString(_iter19);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TestCase struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.functionName = iprot.readString();
        struct.setFunctionNameIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list20 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.inputTypes = new ArrayList<String>(_list20.size);
          String _elem21;
          for (int _i22 = 0; _i22 < _list20.size; ++_i22)
          {
            _elem21 = iprot.readString();
            struct.inputTypes.add(_elem21);
          }
        }
        struct.setInputTypesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list23 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.inputValues = new ArrayList<String>(_list23.size);
          String _elem24;
          for (int _i25 = 0; _i25 < _list23.size; ++_i25)
          {
            _elem24 = iprot.readString();
            struct.inputValues.add(_elem24);
          }
        }
        struct.setInputValuesIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list26 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.outputTypes = new ArrayList<String>(_list26.size);
          String _elem27;
          for (int _i28 = 0; _i28 < _list26.size; ++_i28)
          {
            _elem27 = iprot.readString();
            struct.outputTypes.add(_elem27);
          }
        }
        struct.setOutputTypesIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.expectedOutputValues = new ArrayList<String>(_list29.size);
          String _elem30;
          for (int _i31 = 0; _i31 < _list29.size; ++_i31)
          {
            _elem30 = iprot.readString();
            struct.expectedOutputValues.add(_elem30);
          }
        }
        struct.setExpectedOutputValuesIsSet(true);
      }
    }
  }

}

