/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ch.bfh.progressor.executor.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class executorConstants {

  public static final String TypeContainerArray = "array";

  public static final String TypeContainerList = "list";

  public static final String TypeContainerSet = "set";

  public static final String TypeContainerMap = "map";

  public static final String TypeString = "string";

  public static final String TypeCharacter = "char";

  public static final String TypeBoolean = "bool";

  public static final String TypeByte = "byte";

  public static final String TypeShort = "short";

  public static final String TypeInteger = "int";

  public static final String TypeLong = "long";

  public static final String TypeSingle = "single";

  public static final String TypeDouble = "double";

  public static final String TypeDecimal = "decimal";

}
