/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ch.bfh.progressor.executor.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class executorConstants {

  public static final String TypeContainerArray = "array";

  public static final String TypeContainerList = "list";

  public static final String TypeContainerSet = "set";

  public static final String TypeContainerMap = "map";

  public static final String TypeString = "string";

  public static final String TypeCharacter = "char";

  public static final String TypeBoolean = "bool";

  public static final String TypeInt8 = "int8";

  public static final String TypeInt16 = "int16";

  public static final String TypeInt32 = "int32";

  public static final String TypeInt64 = "int64";

  public static final String TypeFloat32 = "float32";

  public static final String TypeFloat64 = "float64";

  public static final String TypeDecimal = "decimal";

}
