/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ch.bfh.progressor.executor.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-12-10")
public class TestCase implements org.apache.thrift.TBase<TestCase, TestCase._Fields>, java.io.Serializable, Cloneable, Comparable<TestCase> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TestCase");

  private static final org.apache.thrift.protocol.TField FUNCTION_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("functionName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INPUT_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("inputValues", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField EXPECTED_OUTPUT_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("expectedOutputValues", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TestCaseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TestCaseTupleSchemeFactory());
  }

  public String functionName; // required
  public List<String> inputValues; // required
  public List<String> expectedOutputValues; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FUNCTION_NAME((short)1, "functionName"),
    INPUT_VALUES((short)2, "inputValues"),
    EXPECTED_OUTPUT_VALUES((short)3, "expectedOutputValues");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FUNCTION_NAME
          return FUNCTION_NAME;
        case 2: // INPUT_VALUES
          return INPUT_VALUES;
        case 3: // EXPECTED_OUTPUT_VALUES
          return EXPECTED_OUTPUT_VALUES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FUNCTION_NAME, new org.apache.thrift.meta_data.FieldMetaData("functionName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INPUT_VALUES, new org.apache.thrift.meta_data.FieldMetaData("inputValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.EXPECTED_OUTPUT_VALUES, new org.apache.thrift.meta_data.FieldMetaData("expectedOutputValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TestCase.class, metaDataMap);
  }

  public TestCase() {
  }

  public TestCase(
    String functionName,
    List<String> inputValues,
    List<String> expectedOutputValues)
  {
    this();
    this.functionName = functionName;
    this.inputValues = inputValues;
    this.expectedOutputValues = expectedOutputValues;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TestCase(TestCase other) {
    if (other.isSetFunctionName()) {
      this.functionName = other.functionName;
    }
    if (other.isSetInputValues()) {
      List<String> __this__inputValues = new ArrayList<String>(other.inputValues);
      this.inputValues = __this__inputValues;
    }
    if (other.isSetExpectedOutputValues()) {
      List<String> __this__expectedOutputValues = new ArrayList<String>(other.expectedOutputValues);
      this.expectedOutputValues = __this__expectedOutputValues;
    }
  }

  public TestCase deepCopy() {
    return new TestCase(this);
  }

  @Override
  public void clear() {
    this.functionName = null;
    this.inputValues = null;
    this.expectedOutputValues = null;
  }

  public String getFunctionName() {
    return this.functionName;
  }

  public TestCase setFunctionName(String functionName) {
    this.functionName = functionName;
    return this;
  }

  public void unsetFunctionName() {
    this.functionName = null;
  }

  /** Returns true if field functionName is set (has been assigned a value) and false otherwise */
  public boolean isSetFunctionName() {
    return this.functionName != null;
  }

  public void setFunctionNameIsSet(boolean value) {
    if (!value) {
      this.functionName = null;
    }
  }

  public int getInputValuesSize() {
    return (this.inputValues == null) ? 0 : this.inputValues.size();
  }

  public java.util.Iterator<String> getInputValuesIterator() {
    return (this.inputValues == null) ? null : this.inputValues.iterator();
  }

  public void addToInputValues(String elem) {
    if (this.inputValues == null) {
      this.inputValues = new ArrayList<String>();
    }
    this.inputValues.add(elem);
  }

  public List<String> getInputValues() {
    return this.inputValues;
  }

  public TestCase setInputValues(List<String> inputValues) {
    this.inputValues = inputValues;
    return this;
  }

  public void unsetInputValues() {
    this.inputValues = null;
  }

  /** Returns true if field inputValues is set (has been assigned a value) and false otherwise */
  public boolean isSetInputValues() {
    return this.inputValues != null;
  }

  public void setInputValuesIsSet(boolean value) {
    if (!value) {
      this.inputValues = null;
    }
  }

  public int getExpectedOutputValuesSize() {
    return (this.expectedOutputValues == null) ? 0 : this.expectedOutputValues.size();
  }

  public java.util.Iterator<String> getExpectedOutputValuesIterator() {
    return (this.expectedOutputValues == null) ? null : this.expectedOutputValues.iterator();
  }

  public void addToExpectedOutputValues(String elem) {
    if (this.expectedOutputValues == null) {
      this.expectedOutputValues = new ArrayList<String>();
    }
    this.expectedOutputValues.add(elem);
  }

  public List<String> getExpectedOutputValues() {
    return this.expectedOutputValues;
  }

  public TestCase setExpectedOutputValues(List<String> expectedOutputValues) {
    this.expectedOutputValues = expectedOutputValues;
    return this;
  }

  public void unsetExpectedOutputValues() {
    this.expectedOutputValues = null;
  }

  /** Returns true if field expectedOutputValues is set (has been assigned a value) and false otherwise */
  public boolean isSetExpectedOutputValues() {
    return this.expectedOutputValues != null;
  }

  public void setExpectedOutputValuesIsSet(boolean value) {
    if (!value) {
      this.expectedOutputValues = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FUNCTION_NAME:
      if (value == null) {
        unsetFunctionName();
      } else {
        setFunctionName((String)value);
      }
      break;

    case INPUT_VALUES:
      if (value == null) {
        unsetInputValues();
      } else {
        setInputValues((List<String>)value);
      }
      break;

    case EXPECTED_OUTPUT_VALUES:
      if (value == null) {
        unsetExpectedOutputValues();
      } else {
        setExpectedOutputValues((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FUNCTION_NAME:
      return getFunctionName();

    case INPUT_VALUES:
      return getInputValues();

    case EXPECTED_OUTPUT_VALUES:
      return getExpectedOutputValues();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FUNCTION_NAME:
      return isSetFunctionName();
    case INPUT_VALUES:
      return isSetInputValues();
    case EXPECTED_OUTPUT_VALUES:
      return isSetExpectedOutputValues();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TestCase)
      return this.equals((TestCase)that);
    return false;
  }

  public boolean equals(TestCase that) {
    if (that == null)
      return false;

    boolean this_present_functionName = true && this.isSetFunctionName();
    boolean that_present_functionName = true && that.isSetFunctionName();
    if (this_present_functionName || that_present_functionName) {
      if (!(this_present_functionName && that_present_functionName))
        return false;
      if (!this.functionName.equals(that.functionName))
        return false;
    }

    boolean this_present_inputValues = true && this.isSetInputValues();
    boolean that_present_inputValues = true && that.isSetInputValues();
    if (this_present_inputValues || that_present_inputValues) {
      if (!(this_present_inputValues && that_present_inputValues))
        return false;
      if (!this.inputValues.equals(that.inputValues))
        return false;
    }

    boolean this_present_expectedOutputValues = true && this.isSetExpectedOutputValues();
    boolean that_present_expectedOutputValues = true && that.isSetExpectedOutputValues();
    if (this_present_expectedOutputValues || that_present_expectedOutputValues) {
      if (!(this_present_expectedOutputValues && that_present_expectedOutputValues))
        return false;
      if (!this.expectedOutputValues.equals(that.expectedOutputValues))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_functionName = true && (isSetFunctionName());
    list.add(present_functionName);
    if (present_functionName)
      list.add(functionName);

    boolean present_inputValues = true && (isSetInputValues());
    list.add(present_inputValues);
    if (present_inputValues)
      list.add(inputValues);

    boolean present_expectedOutputValues = true && (isSetExpectedOutputValues());
    list.add(present_expectedOutputValues);
    if (present_expectedOutputValues)
      list.add(expectedOutputValues);

    return list.hashCode();
  }

  @Override
  public int compareTo(TestCase other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFunctionName()).compareTo(other.isSetFunctionName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFunctionName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.functionName, other.functionName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInputValues()).compareTo(other.isSetInputValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInputValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inputValues, other.inputValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExpectedOutputValues()).compareTo(other.isSetExpectedOutputValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpectedOutputValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expectedOutputValues, other.expectedOutputValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TestCase(");
    boolean first = true;

    sb.append("functionName:");
    if (this.functionName == null) {
      sb.append("null");
    } else {
      sb.append(this.functionName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("inputValues:");
    if (this.inputValues == null) {
      sb.append("null");
    } else {
      sb.append(this.inputValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("expectedOutputValues:");
    if (this.expectedOutputValues == null) {
      sb.append("null");
    } else {
      sb.append(this.expectedOutputValues);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TestCaseStandardSchemeFactory implements SchemeFactory {
    public TestCaseStandardScheme getScheme() {
      return new TestCaseStandardScheme();
    }
  }

  private static class TestCaseStandardScheme extends StandardScheme<TestCase> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TestCase struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FUNCTION_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.functionName = iprot.readString();
              struct.setFunctionNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INPUT_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list32 = iprot.readListBegin();
                struct.inputValues = new ArrayList<String>(_list32.size);
                String _elem33;
                for (int _i34 = 0; _i34 < _list32.size; ++_i34)
                {
                  _elem33 = iprot.readString();
                  struct.inputValues.add(_elem33);
                }
                iprot.readListEnd();
              }
              struct.setInputValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EXPECTED_OUTPUT_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list35 = iprot.readListBegin();
                struct.expectedOutputValues = new ArrayList<String>(_list35.size);
                String _elem36;
                for (int _i37 = 0; _i37 < _list35.size; ++_i37)
                {
                  _elem36 = iprot.readString();
                  struct.expectedOutputValues.add(_elem36);
                }
                iprot.readListEnd();
              }
              struct.setExpectedOutputValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TestCase struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.functionName != null) {
        oprot.writeFieldBegin(FUNCTION_NAME_FIELD_DESC);
        oprot.writeString(struct.functionName);
        oprot.writeFieldEnd();
      }
      if (struct.inputValues != null) {
        oprot.writeFieldBegin(INPUT_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.inputValues.size()));
          for (String _iter38 : struct.inputValues)
          {
            oprot.writeString(_iter38);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.expectedOutputValues != null) {
        oprot.writeFieldBegin(EXPECTED_OUTPUT_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.expectedOutputValues.size()));
          for (String _iter39 : struct.expectedOutputValues)
          {
            oprot.writeString(_iter39);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TestCaseTupleSchemeFactory implements SchemeFactory {
    public TestCaseTupleScheme getScheme() {
      return new TestCaseTupleScheme();
    }
  }

  private static class TestCaseTupleScheme extends TupleScheme<TestCase> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TestCase struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFunctionName()) {
        optionals.set(0);
      }
      if (struct.isSetInputValues()) {
        optionals.set(1);
      }
      if (struct.isSetExpectedOutputValues()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetFunctionName()) {
        oprot.writeString(struct.functionName);
      }
      if (struct.isSetInputValues()) {
        {
          oprot.writeI32(struct.inputValues.size());
          for (String _iter40 : struct.inputValues)
          {
            oprot.writeString(_iter40);
          }
        }
      }
      if (struct.isSetExpectedOutputValues()) {
        {
          oprot.writeI32(struct.expectedOutputValues.size());
          for (String _iter41 : struct.expectedOutputValues)
          {
            oprot.writeString(_iter41);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TestCase struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.functionName = iprot.readString();
        struct.setFunctionNameIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list42 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.inputValues = new ArrayList<String>(_list42.size);
          String _elem43;
          for (int _i44 = 0; _i44 < _list42.size; ++_i44)
          {
            _elem43 = iprot.readString();
            struct.inputValues.add(_elem43);
          }
        }
        struct.setInputValuesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list45 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.expectedOutputValues = new ArrayList<String>(_list45.size);
          String _elem46;
          for (int _i47 = 0; _i47 < _list45.size; ++_i47)
          {
            _elem46 = iprot.readString();
            struct.expectedOutputValues.add(_elem46);
          }
        }
        struct.setExpectedOutputValuesIsSet(true);
      }
    }
  }

}

